my_tuple = (2,3,4)
print(my_tuple)
print(my_tuple[2])
print(my_tuple[0:3])
print(len(my_tuple))
del my_tuple
my_tuple2 = (1,2,3,4,4)
print(max(my_tuple2))
print(min(my_tuple2))
print(sum(my_tuple2))
print(sum(my_tuple2)/len(my_tuple2))
print(my_tuple2.index(4))
print(my_tuple2.count(4))
my_tuple3 = str('musa,maingi,mzee')
print(my_tuple3)
print(my_tuple3.index('musa'))
print(my_tuple3[0])
print(len(my_tuple3))
